# Generated by Django 2.2.7 on 2019-11-25 06:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_mark', models.CharField(max_length=50)),
                ('car_model', models.CharField(max_length=50)),
                ('car_issue_year', models.IntegerField()),
                ('car_adding_date', models.DateField(default=datetime.datetime(2019, 11, 25, 6, 40, 45, 987007, tzinfo=utc))),
                ('car_status', models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='m', help_text='Car availability', max_length=1)),
                ('car_renter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['car_mark', 'car_model'],
            },
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date_of_loan', models.DateField(default=datetime.datetime(2019, 11, 25, 6, 40, 45, 987924, tzinfo=utc))),
                ('loan_date_of_return', models.DateField()),
                ('loan_car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental.Cars')),
                ('loan_renter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
