# Generated by Django 2.2.7 on 2019-11-25 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_adding_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 25, 6, 43, 32, 759269)),
        ),
        migrations.AlterField(
            model_name='loans',
            name='loan_date_of_loan',
            field=models.DateField(default=datetime.datetime(2019, 11, 25, 6, 43, 32, 759983)),
        ),
    ]
