# Generated by Django 2.2.7 on 2019-11-27 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_auto_20191127_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_adding_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 27, 14, 59, 34, 181781)),
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan_car',
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_car',
            field=models.ManyToManyField(to='rental.Car'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date_of_loan',
            field=models.DateField(default=datetime.datetime(2019, 11, 27, 14, 59, 34, 182773)),
        ),
    ]
