# Generated by Django 2.2.7 on 2019-11-27 15:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_auto_20191127_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_adding_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 27, 15, 4, 29, 824286)),
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan_car',
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental.Car'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date_of_loan',
            field=models.DateField(default=datetime.datetime(2019, 11, 27, 15, 4, 29, 825285)),
        ),
    ]
