# Generated by Django 2.2.7 on 2019-11-27 23:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_auto_20191127_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_adding_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 27, 23, 19, 49, 183506)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date_of_loan',
            field=models.DateField(default=datetime.datetime(2019, 11, 27, 23, 19, 49, 183506)),
        ),
    ]
