# Generated by Django 2.2.7 on 2019-11-28 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0007_auto_20191127_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_adding_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 28, 9, 11, 39, 69038)),
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
