# Generated by Django 2.2.7 on 2019-11-28 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0008_auto_20191128_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_rent_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 28, 9, 56, 38, 453467)),
        ),
        migrations.AddField(
            model_name='car',
            name='car_return_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 28, 9, 56, 38, 453467)),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_adding_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 28, 9, 56, 38, 453467)),
        ),
    ]
