# Generated by Django 2.2.7 on 2019-11-28 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0009_auto_20191128_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_adding_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 28, 12, 2, 14, 562933)),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_rent_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 11, 28, 12, 2, 14, 562933), null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_return_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 11, 28, 12, 2, 14, 562933), null=True),
        ),
    ]
